# Generated by Django 3.2.8 on 2022-04-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.TextField()),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caches.cache')),
            ],
        ),
        migrations.AddField(
            model_name='cache',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caches.session'),
        ),
    ]
