# Generated by Django 3.2.8 on 2022-04-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cache',
            name='image',
        ),
    ]
