# Generated by Django 3.2.8 on 2022-04-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0002_remove_cache_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='acomplished',
            field=models.BooleanField(default=False),
        ),
    ]
