# Generated by Django 3.2.8 on 2022-04-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0003_cache_acomplished'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='image',
            field=models.ImageField(default='llit.jpeg', upload_to=''),
        ),
        migrations.CreateModel(
            name='Submmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='llit.jpeg', upload_to='')),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caches.cache')),
            ],
        ),
    ]
