# Generated by Django 3.2.8 on 2022-05-01 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caches', '0004_auto_20220430_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
